### ISSUE TITLE
Verification mail cannot be sent?

### ISSUE THREAD

**Issue by salamander-mh** [getsentry/sentry#10064]
## Important Details
**here I can send the mail successfully:**
![image](https://user-images.githubusercontent.com/16663435/46719298-25741b80-cca0-11e8-8690-2fa37e3b789b.png)

However, I can not send the verification mail.

 from the smtp logs
```
Size of off_t: 8
smtp_1       |   289 delivering 1gA8wT-00004e-59
smtp_1       |   289 R: dnslookup for energy3456789@gmail.com
smtp_1       |   290 T: remote_smtp for energy3456789@gmail.com
smtp_1       |   290 Connecting to gmail-smtp-in.l.google.com [2404:6800:4008:c07::1b]:25 ... failed: Cannot assign requested address
smtp_1       |   290 LOG: MAIN
smtp_1       |   290   H=gmail-smtp-in.l.google.com [2404:6800:4008:c07::1b] Cannot assign requested address
smtp_1       |   290 Connecting to gmail-smtp-in.l.google.com [108.177.97.26]:25 ... failed: Connection timed out (timeout=5m)
smtp_1       |   290 LOG: MAIN
smtp_1       |   290   H=gmail-smtp-in.l.google.com [108.177.97.26] Connection timed out
smtp_1       |   290 Connecting to alt1.gmail-smtp-in.l.google.com [2607:f8b0:4003:c19::1a]:25 ... failed: Cannot assign requested address
smtp_1       |   290 LOG: MAIN
smtp_1       |   290   H=alt1.gmail-smtp-in.l.google.com [2607:f8b0:4003:c19::1a] Cannot assign requested address


```

I'm using On-Premise docker and have setup the SMTP.

**Comment by markstory** [comment]
Your SMTP connnection is timing out.

**Comment by salamander-mh** [comment]
I have solved the problem. add environment variables to docker-compose.yml:
```
x-defaults: &defaults
  restart: unless-stopped
  build: .
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp

  environment:
    # Run `docker-compose run web config generate-secret-key`
    # to get the SENTRY_SECRET_KEY value.
    SENTRY_SECRET_KEY: ''
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: 'smtp.exmail.qq.com' 
    SENTRY_SERVER_EMAIL: ''
    SENTRY_EMAIL_HOST: ''
    SENTRY_EMAIL_PORT: ''
    SENTRY_EMAIL_USER: ''
    SENTRY_EMAIL_PASSWORD: ''
    SENTRY_EMAIL_USE_TLS: true
    SENTRY_ENABLE_EMAIL_REPLIES: ''
```
