### ISSUE TITLE
[9.0.0] SMTPServerDisconnected

### ISSUE THREAD

**Issue by dmke** [getsentry/sentry#10648]
## Important Details

How are you running Sentry?

* On-Premise docker [Version xyz]
* Saas (sentry.io)
* [x] Other: **On-Premise, manual installation.**

## Description

I recently upgraded Sentry from 8.22.0 to 9.0.0. Since then, e-mail delivery fails with `SMTPServerDisconnected: Connection unexpectedly closed: timed out`, see shared issue: https://sentry.digineo.de/share/issue/d15c19da2ee94ebdb872589ca9f796e7/

Sentry is configured to use a local smtp server (Postfix; as relay host). I have verified that this server is running (`127.0.0.1:25` and `[::1]:25`) and still capable of sending e-mails. It does not time out.

## Steps to Reproduce

1. Install Sentry as per https://docs.sentry.io/server/installation/python/
2. Use the following configuration

    <details>
    <summary>Systemd-Units</summary>

    ```sh
    # /lib/systemd/system/sentry-{web,worker,cron}.service
    # ...
    [Service]
    Environment=SENTRY_CONF=/etc/sentry
    # ...
    ```

    </details>

    <details>
    <summary>/etc/sentry/config.yml</summary>

    ```yaml
    # /etc/sentry/config.yml
    mail.backend:   'smtp'  # Use dummy if you want to disable email entirely
    mail.host:      'localhost'
    mail.port:      25
    # mail.username:  ''
    # mail.password:  ''
    mail.use-tls:   false
    mail.from:      'noreply+sentry@digineo.de'
    # mail.enable-replies: false
    # mail.reply-hostname: ''
    # mail.mailgun-api-key: ''
    system.secret-key: '<omitted>'
    redis.clusters:
      default:
        hosts:
          0:
            host: 127.0.0.1
            port: 6379
    filestore.backend: 'filesystem'
    filestore.options:
      location: '/home/sentry/tmp'
    ```

    </details>

    <details>
    <summary>/etc/sentry/sentry.conf.py</summary>

    ```python
    # /etc/sentry/sentry.conf.py
    from sentry.conf.server import *
    import os.path

    CONF_ROOT = os.path.dirname(__file__)
    DATABASES = {
        'default': {
            # <omitted>
        }
    }
    SENTRY_USE_BIG_INTS = True
    SENTRY_SINGLE_ORGANIZATION = True
    DEBUG = False
    # CACHES = {
    #     'default': {
    #         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
    #         'LOCATION': ['127.0.0.1:11211'],
    #     }
    # }
    SENTRY_CACHE = 'sentry.cache.redis.RedisCache'
    BROKER_URL = 'redis://localhost:6379'
    SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'
    SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'
    SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'
    SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'
    SENTRY_DIGESTS = 'sentry.digests.backends.redis.RedisBackend'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True
    # FORCE_SCRIPT_NAME = '/sentry'
    SENTRY_WEB_HOST = '0.0.0.0'
    SENTRY_WEB_PORT = 9000
    SENTRY_WEB_OPTIONS = {
        # 'workers': 3,  # the number of web workers
        # 'protocol': 'uwsgi',  # Enable uwsgi protocol instead of http
    }
    ```

    </details>

3. Install Postfix as relayhost

    <details>
    <summary>/etc/postfix/main.cf</summary>

    ```sh
    smtpd_banner = $myhostname ESMTP $mail_name
    biff = no
    append_dot_mydomain = no
    readme_directory = no
    myorigin = /etc/mailname
    smtp_tls_security_level = may
    smtp_dns_support_level = enabled

    # Do not accept mail from the network.
    inet_interfaces = loopback-only

    # Disable local mail delivery.
    mydestination =

    # The next-hop destination of non-local mail.
    relayhost = <omitted>
    ```

    </details>

### What you expected to happen

Sentry should continue delivering alerts/weekly digests.

### Possible Solution

I don't know. I'd love to configure `sendmail` instead of local smtp.
