### ISSUE TITLE
Azure DevOps Accosiate Commits

### ISSUE THREAD

**Issue by BillChirico** [getsentry/sentry#11127]
Hello,

I've connected my Azure DevOps repository to Sentry, but it is not associating commits. Do I need to add a build task in my build pipeline?

**Comment by markstory** [comment]
Are you looking to get suspect commits working, or see commit links in an issue's 'Comments' sub tab?

Getting suspect commits working requires using [releases and setting commits for each release](https://docs.sentry.io/workflow/releases/?platform=javascript#b-associate-commits-with-a-release) this is required so that sentry can compare the releases a issue was created in with the files changed in a given release.

**Comment by BillChirico** [comment]
Is there an easy way to do this from an Azure DevOps build pipeline?

**Comment by markstory** [comment]
@BillChirico I'm not sure, I've never used Azure DevOps. If you can run bat/shell scripts you should be able to download & use `sentry-cli` or make the relevant API calls.

**Comment by DarthSonic** [comment]
@BillChirico did you manage to get commits associated in Sentry over Azure DevOps? Having the same problem.

**Comment by BillChirico** [comment]
@DarthSonic I did not unfortunately

**Comment by josh-degraw** [comment]
@BillChirico Have you been able to get it working for you? I was able to figure out a way to do it, if you're interested I can post the yaml here.

**Comment by BillChirico** [comment]
@josh-degraw I have not, could you please post it?

**Comment by josh-degraw** [comment]
So I wrote these scripts as templates to use in multiple pipelines, and actually have split them out into separate templates, so your mileage may vary, but here are all of the scripts I have used for this. 

Note: I stored my sentry auth token as a secret variable in a group called sentry. If you do similar just make sure you've referenced the variable group in the final pipeline file e.g.:
```yml
variables:
- group: Sentry
```

```yml
parameters:
  sentryReleaseVersion: "$(Build.BuildNumber)"
  sentryReleaseEnvironment: Production
  sentryOrgName: ''
  sentryProjectName: ''

steps:

  # This just makes sure that all required parameters are found
  - bash: |
      if [ -z "$SENTRY_ORG" ]; then
        echo "##vso[task.logissue type=error;]Missing template parameter \"sentryOrgName\""
        echo "##vso[task.complete result=Failed;]"
      fi
      if [ -z "$SENTRY_PROJECT" ]; then
        echo "##vso[task.logissue type=error;]Missing template parameter \"sentryProjectName\""
        echo "##vso[task.complete result=Failed;]"
      fi
    displayName: Check for required parameters
    env:
      SENTRY_ORG: ${{ parameters.sentryOrgName }}
      SENTRY_PROJECT: ${{ parameters.sentryProjectName }}
      
  #This script installs the cli on the build server
  - bash: |
      # Install cli
      curl -sL https://sentry.io/get-cli/ | bash
      
      # Verify Installation
      sentry-cli --help
    displayName: 'Install cli'

  # This script writes a .sentryclirc file to propogate config to downstream commands
  - bash: |
      echo Writing sentry config file
      
      echo "
      [defaults]
      url = <<YOUR SENTRY ROOT URL>>
      org = $SENTRY_ORG
      project = $SENTRY_PROJECT
      
      [auth]
      token= $SENTRY_AUTH_TOKEN
      
      " > ./.sentryclirc
      
      cat ./.sentryclirc
    displayName: 'Write config file'
    env: 
      SENTRY_PROJECT: ${{ parameters.sentryProjectName }}
      SENTRY_ORG: ${{ parameters.sentryOrgName }}
      SENTRY_AUTH_TOKEN: $(Sentry.AuthToken) # Sentry.AuthToken is defined in the Sentry Variable group, marked as secret so must be passed in as environment var
  
  # This script informs sentry of the release
  - bash: |
      # Assumes you're in a git repository          
      echo "Version ${{parameters.sentryReleaseVersion}}; Project ${{parameters.sentryProjectName}}"
      
      echo Creating a release
      echo "sentry-cli releases new ${{parameters.sentryReleaseVersion}} -p ${{parameters.sentryProjectName}}"
      
      sentry-cli releases new ${{parameters.sentryReleaseVersion}} -p ${{parameters.sentryProjectName}} --log-level=debug
      
      echo Associating commits with the release
      echo "sentry-cli releases set-commits '${{parameters.sentryReleaseVersion}}' --auto"
      sentry-cli releases set-commits '${{parameters.sentryReleaseVersion}}' --auto --log-evel=debug

    displayName: 'Synchronize Commit data'
  
  # This script deploys a release. I run this script separately as part of a release pipeline
  - bash: |
      # Assumes you're in a git repository      
      sentry-cli releases deploys ${{parameters.sentryReleaseVersion}} new -e ${{parameters.sentryReleaseEnvironment}}      
    displayName: 'Deploy Sentry Release'

```
