### ISSUE TITLE
[9.1] After migrations, graphs don't show past events

### ISSUE THREAD

**Issue by guidoilbaldo** [getsentry/sentry#12810]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 9.1.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I'm running Sentry with a simple docker-compose that creates memcached, redis, cron, workers and web interface for Sentry. I've got an external PostgreSQL as a DB.
Yesterday I decided to upgrade from 9.0 to 9.1 and, to do so, I updated docker image version inside docker-compose.yml.
I then stopped all the containers, force-recreated them and went inside sentry-web container to run migrations. The migrations went good, so I restarted the containers one last time and, once inside Sentry GUI, I still had all the events present but graphs inside projects were like erased. After some minutes and some new events, I again started to see graphs populating, but events arrived before the upgrade are not shown.
I post an image to show the problem. In the below graph, you see a lot of no events before a certain point in time (when I updated Sentry), but events are there, they're not shown on graph.

<img width="362" alt="Screenshot 2019-04-17 at 08 25 32" src="https://user-images.githubusercontent.com/6077718/56265727-97636c80-60ea-11e9-9141-87d3f6fc5934.png">

## Steps to Reproduce

1. Have a Sentry on-prem running 9.0 version
2. Update docker image to 9.1 and force-recreate containers
3. Inside sentry-web container, run migrations
4. Restart containers

Good items to include here include:

```yaml
version: '3.5'

x-sentry: &base
  restart: unless-stopped
  image: sentry:9.1.0
  env_file: /data/config/sentry.env
  depends_on:
    - memcached
  links:
    - redis:redis
  volumes:
    - /data/sentry:/var/lib/sentry/files

services:
  sentry:
    <<: *base
    container_name: web
    restart: unless-stopped
    ports:
      - 9000:9000
  worker:
    <<: *base
    container_name: worker
    restart: unless-stopped
    command: run worker
  cron:
    <<: *base
    container_name: cron
    restart: unless-stopped
    command: run cron
  memcached:
    image: memcached:1.5.12
    container_name: memcached
    restart: unless-stopped
  redis:
    image: redis:5.0.3
    container_name: redis
    restart: always
    ports:
      - 6379:6379
```

### What you expected to happen

After migrations run, I expected to see graphs with events as they were before the upgrade

### Possible Solution

I guess I have to recreate graphs so that they could show events already present again, but I don't know if it exists a command or a way to do so.
