### ISSUE TITLE
sentry worker error: preprocess.failed.empty 

### ISSUE THREAD

**Issue by Troy456** [getsentry/sentry#16198]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2 onbuild]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Hey. My sentry  has been running steadily for more than three months, but can't receive any message from sentry sdk on yesterday. I'm using the version of sentry: 9.1.2-onbuild. This error in sentry-worker is shown here.

07:06:05 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:aebd6b3ed2874cc6b6138b45fef518aa:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:15e7e0b7149348f7aa9817d47e1161bc:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:dea3dc2b4bf340b985397412b0d16960:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:887e0bac3bb645939c68919150629b00:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:774efaa8d0d048ce97bcd5319f53b769:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:810981559a154a679a355860ea821d05:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:e3700aab41e9494e8fefb3e100ac37b0:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:ceaf5a9c815c403e80efdfef76114345:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:d8db0c584d9849bd8230aaab3420adc6:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:a47cb390d31144ecab09a06507ddee2f:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:35e254377a9c4b3ea4da752492410c05:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:5fcf371ee8054ba9b5f43a45664c2440:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:372da8c6e055480caf9579956f693e5f:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:69f32af07084477ba22bac5361ba45ca:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:a8097536b8d845f59519384ebc2250e0:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:f762c874ed2842e8a2aae4e39abc3f9f:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:d4b829e058b945a589dba6f9f46c920a:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:3b0f43f974c948b49c629d2041cc9dbf:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:5e198c0ab792473ca2e862a22f24798b:7')
07:06:06 [ERROR] sentry.errors.events: process.failed.empty (cache_key=u'e:2716686d2f594c848922e99dd38a9e50:7')
07:06:06 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:ed5fca670f2944279cbc1b8b3af41875:7')

### Possible Solution

Sentry can work normally when i use new redis cluster. but i want to know how to avoid the error.

**Comment by BYK** [comment]
Hi,

Did you make any changes to your system since just before this issue has started? Can you provide more information about your setup?

**Comment by Troy456** [comment]
I don't make any changes to my system.

When i copy the error redis data to a new redis server ,can't reproduce the issue, Sentry worked without any problem.

The redis version is 4.0.6, postgresql server version is 11.
Sentry start command is as below:

```shell
#web
docker run -d -v /data/sentry/sentry-files:/data/sentry/sentry-files -v /data/sentry/config/:/home/sentry/ -p 9000:9000 -e "SENTRY_CONF=/home/sentry/" --restart=always --name sentry-web sentry:9.1.2-onbuild  sentry run web
#worker
docker run -d -v /data/sentry/sentry-files:/data/sentry/sentry-files -v /data/sentry/config/:/home/sentry/ -e "SENTRY_CONF=/home/sentry/" --restart=always --name sentry-worker  sentry:9.1.2-onbuild  sentry run worker
#cron
docker run -d -v /data/sentry/sentry-files:/data/sentry/sentry-files -v /data/sentry/config/:/home/sentry/ -e "SENTRY_CONF=/home/sentry/" --restart=always --name sentry-cron sentry:9.1.2-onbuild  sentry run cron
```

The redis config in config.yml is :

```yaml
redis.clusters:
  default:
    hosts:
      0:
        host: 192.168.75.133
        port: 6379
        db: 0
  ratelimiter:
    hosts:
      0:
        host: 192.168.75.133
        port: 6379
        db: 1
  buffer:
    hosts:
      0:
        host: 192.168.75.133
        port: 6379
        db: 2
  quota:
    hosts:
      0:
        host: 192.168.75.133
        port: 6379
        db: 3
  digests:
    hosts:
      0:
        host: 192.168.75.133
        port: 6379
        db: 4
  tsdb:
    hosts:
      0:
        host: 192.168.75.133
        port: 6379
        db: 5
      1:
        host: 192.168.75.132
        port: 6379
        db: 5

```

The redis config in  sentry.conf.py is :

```python
SENTRY_CACHE = 'sentry.cache.redis.RedisCache'
BROKER_URL = 'redis://192.168.75.133:6379/7'
SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'
SENTRY_RATELIMITER_OPTIONS = {
    'cluster': 'ratelimiter',
}
SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'
ENTRY_BUFFER_OPTIONS = {
    'cluster': 'buffer',
}
SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'
SENTRY_QUOTA_OPTIONS = {
    'cluster': 'quota',
}
SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'
SENTRY_TSDB_OPTIONS = {
    'cluster': 'tsdb',
}
SENTRY_DIGESTS = 'sentry.digests.backends.redis.RedisBackend'
SENTRY_DIGESTS_OPTIONS = {
    'capacity': 100,
    'cluster': 'digests',
}
```
