### ISSUE TITLE
[Errno 524] Unknown error 524 when upload the sourcemaps

### ISSUE THREAD

**Issue by kevinyan** [getsentry/sentry#16462]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [briefly describe your environment]
    * I installed sentry 9.1.2 through [K8S's helm](https://github.com/helm/charts/tree/master/stable/sentry)

## Description

I upload the generated sourcemap ，bug got an internal error `Unknown error 524`

### 1. How I install the sentry system
I installed sentry 9.1.2 through K8S's helm ，The code is as follows. 
 
```
filestore:
    backend: filesystem
    filesystem:
        path: /var/lib/sentry/files
        persistence:
            accessMode: ReadWriteMany
            enabled: true
            persistentWorkers: true
            size: 20Gi
            storageClass: bdsentry
    gcs:
        credentialsFile: credentials.json
    s3: {}
```
### 2. I use [baiducloud'cfs ](https://cloud.baidu.com/doc/CCE/s/ejxpppgp0#%E5%8A%A8%E6%80%81pvpvc%E6%96%B9%E5%BC%8F%E6%8C%82%E8%BD%BDcfs) 
this is what we call it NFS and I can get the mounted volums

![image](https://user-images.githubusercontent.com/2274844/72420435-ab431880-37b9-11ea-8160-49fb11353cbb.png)

### 3. Upload soucemaps
I upload the generated sourcemaps through the plugin `@sentry/webpack-plugin` ,but got a 500 error
![image](https://user-images.githubusercontent.com/2274844/72421025-b480b500-37ba-11ea-91be-a59cb9fc3ca6.png)

### 4. The sentry platform  reported a internal error
```
IOError/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/
in sentry/models/file.py
[Errno 524] Unknown error 524
```
![image](https://user-images.githubusercontent.com/2274844/72421035-bcd8f000-37ba-11ea-8699-f772b3caa661.png)
![image](https://user-images.githubusercontent.com/2274844/72421041-c1050d80-37ba-11ea-9ae7-fcdc7ef5511f.png)

### What you expected to happen

I expect the sourcemap can upload successfully
