### ISSUE TITLE
Error events are accepted 

### ISSUE THREAD

**Issue by Fgruntjes** [getsentry/sentry#22789]
## Important Details

How are you running Sentry?
Using the helm chart https://github.com/sentry-kubernetes/charts running version Sentry 20.12.1bade073
with values
```
web:
    hpa:
        enabled: false
        cputhreshold: 60
        minpods: 1
        maxpods: 10
    replicacount: 1
    resources:
        requests:
            cpu: 300m
            memory: 500Mi
    env:
    -   name: SENTRY_SLACK_CLIENT_ID
        value: "XXXXXXX"
    -   name: SENTRY_SLACK_CLIENT_SECRET
        value: "XXXXXXX"
    -   name: SENTRY_SLACK_VERIFICATION_TOKEN
        value: "XXXXXXX"
    -   name: SENTRY_VSTS_CLIENT_ID
        value: "XXXXXXX"
    -   name: SENTRY_VSTS_CLIENT_SECRET
        value: "XXXXXXX"

cron:
    replicacount: 1
    resources:
        requests:
            cpu: 150m
            memory: 200Mi
    env:
    -   name: SENTRY_SLACK_CLIENT_ID
        value: "XXXXXXX"
    -   name: SENTRY_SLACK_CLIENT_SECRET
        value: "XXXXXXX"
    -   name: SENTRY_SLACK_VERIFICATION_TOKEN
        value: "XXXXXXX"
    -   name: SENTRY_VSTS_CLIENT_ID
        value: "XXXXXXX"
    -   name: SENTRY_VSTS_CLIENT_SECRET
        value: "XXXXXXX"

worker:
    replicacount: 1
    resources:
        requests:
            cpu: 150m
            memory: 200Mi
    env:
    -   name: SENTRY_SLACK_CLIENT_ID
        value: "XXXXXXX"
    -   name: SENTRY_SLACK_CLIENT_SECRET
        value: "XXXXXXX"
    -   name: SENTRY_SLACK_VERIFICATION_TOKEN
        value: "XXXXXXX"
    -   name: SENTRY_VSTS_CLIENT_ID
        value: "XXXXXXX"
    -   name: SENTRY_VSTS_CLIENT_SECRET
        value: "XXXXXXX"
system:
    url: "XXXXXXX"
    adminEmail: "XXXXXXX"
    secretKey: "XXXXXXX"

mail:
    backend: smtp
    from: XXXXXXX
    host: XXXXXXX
    port: 25
    useTls: true
    username: sentry
    password: XXXXXXX

postgresql:
    enabled: true
    persistence:
        size: 30Gi

kafka:
    enabled: true

filestore:
    backend: s3
    s3:
        accessKey: "XXXXXXX"
        secretKey: "XXXXXXX"
        bucketName: "XXXXXXX"
        endpointUrl: "XXXXXXX"
        region_name: "XXXXXXX"

sentry:
    features:
        orgSubdomains: true

service:
    type: ClusterIP

nginx:
    enabled: false

ingress:
    enabled: true
    hostname: XXXXXXX
    tls:
    -   hosts:
        - XXXXXXX
        secretName: sentry-ingress-cert
    annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/use-regex: "true"
```

## Description

Events are being accepted with an incorrect DSN

## Steps to Reproduce

- Create a project and note the ID
- Send curl request to push an incorrect sentry event:
```
curl --data '{"error": "someerror"}' \
  -H 'Content-Type: application/json' \
  -H "X-Sentry-Auth: Sentry sentry_version=7, sentry_key=3f642033bc56406d838f8a1d4a7321af, sentry_client=raven-bash/0.1" \
  https://XXXX/api/9/store/
```

I do see these logs in the `sentry-relay` pod:
```
2020-12-17T22:40:53Z [relay_server::actors::events] ERROR: project state for key 43f7e281d3094142af2c7b7522673de5 is missing key id
2020-12-17T22:41:18Z [relay_server::actors::events] ERROR: project state for key 43f7e281d3094142af2c7b7522673de5 is missing key id
2020-12-17T22:41:35Z [relay_server::actors::events] ERROR: project state for key e066ddcb8eb24132856691078a934fd8 is missing key id
2020-12-17T22:41:48Z [relay_server::actors::events] ERROR: project state for key 43f7e281d3094142af2c7b7522673de5 is missing key id
```

### What you expected to happen

The event should be dropped

### Possible Solution

Because most sentry instances running in K8S are not accessible from the outside I expect we just configured something wrong and there is some kind of settings in Sentry to force these keys. Any help will be greatly appreciated!

**Comment by Fgruntjes** [comment]
Hi guys,

Any suggestions on this would be greatly appriciated. Is there some kind of setting to ignore the key value for example?

**Comment by teebu** [comment]
Using same version, `Sentry 20.12.1bade073` on a k8 cluster, similar setup. My errors get recorded in sentry, but in relay I am seeing the same error, 

```

2021-01-06 16:08:26 | 2021-01-07T00:08:26Z [relay_server::actors::events] ERROR: project state for key d66a38c9b9a344eaa53a46987a1399dc is missing key id
-- | --
```

**Comment by lff0305** [comment]
Exactly the same issue (Sentry 20.12.1bade073).
Any event with correct key or wrong key is accepted and save to project, while the log of 
project state for key zzzzzzzzzzzzzzzzzzzzzzzzzz is missing key id
appears in relay server

**Comment by untitaker** [comment]
Hey, does this still happen with 21.1?

**Comment by nodomain** [comment]
Jumping in - seeing the same errors with 21.1. in Cloudwatch:

![image](https://user-images.githubusercontent.com/104389/106397141-2babda00-640c-11eb-9a70-96a3013a745f.png)


Disclaimer: using https://github.com/Rungutan/sentry-fargate-cf-stack for hosting my "on premise" version.

**Comment by untitaker** [comment]
We cannot reproduce this issue with https://github.com/getsentry/onpremise. Invalid DSNs are rejected and the error does not appear in logs. We suspect that either:

* your sentry images are out of sync with relay images
* requests going from relay to sentry are somehow losing their query parameters

In order to assess this issue properly I need:

* versions/shas of the images you are running. Alternatively, the relay version and the sentry version as reported via their CLIs
* if that is unrevealing, a wireshark dump from a couple requests that go from relay to sentry. They should all hit one particular endpoint that is called `/api/0/relay/projectconfig`.

**Comment by Antiarchitect** [comment]
I have the same issue. Found out investigating this: https://github.com/getsentry/sentry/issues/23161 I've turned off DSN Key for noisy project and waiter for a couple of hours (I thought it was a big backlog for tasks to be processed) but anyway sentry events are still accepted despite of DSN is disabled.

**Comment by Antiarchitect** [comment]
Possibly I found the solution for Sentry Helm Chart case. It appears by default relay is working in `proxy` mode. In order to change that you should first configure chart properly:
```
relay:
  mode: managed
```
After that go to Settings -> Relay in Sentry Web interface and register the relay using its public key.

**Comment by prasus** [comment]
I have got an on-premise sentry setup deployed with sentry/sentry chart version 8.1.2  and have the same issue, The errors events are always accepted and and also the rate-limit settings are not honored. 

I have redeployed the chart after making the following change, 

```
From:

relay:
  mode: proxy

To:

relay:
  mode: managed
```

But the sentry relay pod fails with the below error after the change, I had to rollback the changes to make it work again. 

```
2021-06-07T04:13:17Z [relay_server::actors::upstream] INFO: registering with upstream (http://sentry-web:9000/)
2021-06-07T04:13:17Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: could not send request using actix-web client
  caused by: Server disconnected
  caused by: Server disconnected
2021-06-07T04:13:34Z [relay_server::actors::upstream] INFO: registering with upstream (http://sentry-web:9000/)
2021-06-07T04:13:34Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: could not send request using actix-web client
  caused by: Server disconnected
  caused by: Server disconnected
```

Any ideas? Thanks 🙂
