### ISSUE TITLE
Email setting related issue while upgrading from 8.0.4 to 8.3.2

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#3131]
As suggested here https://docs.getsentry.com/on-premise/server/warnings/, I added email related setting in config.yml. I restarted sentry and I get an email configuration form that I did not fill thinking that the email configuration will be used from config.yml.

The email is not working now and the email setting I see in admin page is not the setting that I have in config.yml. Also I cant edit the email config in admin. What do you think I missed?

**Comment by mattrobenolt** [comment]
Can you give me an example of what you updated it to? You can obviously censor relevant bits.

**Comment by sul4bh** [comment]
Here is my config:

```
mail.backend: 'django.core.mail.backends.smtp.EmailBackend'
mail.host: 'smtp.mailgun.org'
mail.password: '***'
mail.username: '***'
mail.port: '25'
mail.use-tls: 'False'
mail.from: 'logging@***'
redis.clusters:
  default:
    hosts:
      0:
        host: 127.0.0.1
        port: 6379
```

**Comment by mattrobenolt** [comment]
And did you restart everything and remove the old config variables?

**Comment by sul4bh** [comment]
Yes I did.

**Comment by mattrobenolt** [comment]
What happens when you run `sentry config get mail.host`? You should be able to access these from command line to confirm.

**Comment by sul4bh** [comment]
I get an error:
`TypeError: 'mail.use-tls': got <type 'str'>, expected boolean`

**Comment by mattrobenolt** [comment]
Ah, so that's what I suspected. :) Your port to yaml was slightly wrong. Your types are wrong.

You'd need:

```yaml
mail.backend: 'django.core.mail.backends.smtp.EmailBackend'
mail.host: 'smtp.mailgun.org'
mail.password: '***'
mail.username: '***'
mail.port: 25
mail.use-tls: false
mail.from: 'logging@***'
redis.clusters:
  default:
    hosts:
      0:
        host: 127.0.0.1
        port: 6379
```

Notice the changes to `mail.use-tls` and `mail.port`. You're setting it to the string `False` and not the boolean value. And the port as a string instead of integer.
