### ISSUE TITLE
When adding a new project after reimporting old projects, fails due to postgres sequence not having been reset

### ISSUE THREAD

**Issue by israelshirk** [getsentry/sentry#3840]
## Situation

I maintain a set of docker containers for developers to use.  As much as possible, these are plug-and-play - so a user just runs `docker-compose up` and gets a full stack with all requisite services pre-configured and databases loaded with seed data.  For sentry's part, I simply use `sentry dump` and `sentry import` to have sentry's dataset ready to go - which for the most part works flipping great.
## Setup to repeat

Set up a sentry installation in docker and add a project.
### sentry.json (initial)

``` json
[]
```
### Dockerfile

``` dockerfile
FROM sentry:8.5

ADD docker-entrypoint.sh /entrypoint.sh
ADD sentry.json /sentry.json

USER sentry
```
### docker-entrypoint.sh

``` bash
#!/bin/bash

set -e

# first check if we're passing flags, if so
# prepend with sentry
if [ "${1:0:1}" = '-' ]; then
    set -- sentry "$@"
fi

case "$1" in
    start)
        echo "Migrations starting..."

        sleep 15
        sentry upgrade --noinput || (echo "Sentry upgrade failed"; exit 1)
        sentry createuser "--email=dev@nlpsecure.com" "--password=test123" "--superuser" "--no-input" || echo "Sentry createuser failed - may already be there"

        echo "Migrations completed (hopefully)"

        echo "Running import"
        sentry import /sentry.json
        echo "Done running import"

        set -- sentry "$@"
    ;;
    run|celery|cleanup|config|createuser|devserver|django|export|help|import|init|plugins|queues|repair|shell)
        echo "Waiting 120 seconds for database to be ready..."
        sleep 120
        echo "Starting sentry workers..."

        set -- sentry "$@"
    ;;
    generate-secret-key)
        exec sentry config generate-secret-key
    ;;
esac

exec "$@"
```
### docker-compose.yml:

``` yaml
redis:
    container_name: redis
    image: redis
    labels:
        SERVICE_ID: redis
    command: redis-server --appendonly yes
    dns: 172.20.254.2
    dns_search: docker
    ports:
        - "6379:6379"

postgres:
    container_name: postgres
    image: postgres
    labels:
        SERVICE_ID: postgres
    environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: sentry
    restart: always

# Sentry and sentry workers - error tracking

sentry:
    container_name: sentry
    image: gcr.io/nlp-development-tools/sentry:latest
    ports:
        - "9000:9000"
    labels:
        SERVICE_ID: sentry
    command: "start"
    links:
        - "redis:redis"
        - "postgres:postgres"
    environment:
        SENTRY_POSTGRES_PORT: "5432"
        SENTRY_REDIS_PORT: "6379"
        SENTRY_SECRET_KEY: "sldakfjalsdkfjlasdkfjasldkfj"
    restart: always

sentry-celery-beat:
    container_name: sentry-celery-beat
    image: gcr.io/nlp-development-tools/sentry:latest
    links:
        - "redis:redis"
        - "postgres:postgres"
    labels:
        SERVICE_ID: sentry-celery-beat
    command: "run cron"
    environment:
        SENTRY_POSTGRES_PORT: "5432"
        SENTRY_REDIS_PORT: "6379"
        SENTRY_SECRET_KEY: "alsdfjkasldkfjlasdkfj"
    restart: always

sentry-celery-worker1:
    container_name: sentry-celery-worker1
    image: gcr.io/nlp-development-tools/sentry:latest
    links:
        - "redis:redis"
        - "postgres:postgres"
    labels:
        SERVICE_ID: sentry-celery-worker
    command: "run worker"
    environment:
        SENTRY_POSTGRES_PORT: "5432"
        SENTRY_REDIS_PORT: "6379"
        SENTRY_SECRET_KEY: "asldkfjasldkfjasldkfjlasdkfj"
    restart: always
```
#### Sentry export created with:

``` bash
#!/bin/bash

docker exec -it sentry sentry export -q > sentry.json

cat sentry.json | jq
```
## Run and add a project and let workers start up.

Run an export to sentry.json so you get your whole project, and then restart.  It should just come online with all your projects, users, etc.  Awesome!
## Issue

After having done this process, there are several situations in which sentry runs into primary key conflicts.  It looks like Postgres is restarting its sequences at primary key 1, while Sentry's import has already inserted ID=1.  The easiest to duplicate is to just add a new project when there's already one in place.  Workers also dump some info about primary key conflicts into their error output and internal reporting during their startup/checkin.
## Possible solutions

I'm likely less familiar with Postgres than you guys, but it seems that just iterating through all the affected tables during import and adjusting the current sequence number to the max value would resolve it.

http://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync
## Eternal gratefulness

Thanks for all that you guys do, and I love your product!  I'm slowly and surely working The Management towards purchasing a fully supported on-premise copy.
