### ISSUE TITLE
Fresh install error: AssertionError sentry.eventstream.kafka.backend in _build_consumer 

### ISSUE THREAD

**Issue by ssjunior** [getsentry/sentry#40120]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

Sentry 22.10.0.dev0

### Steps to Reproduce

Do a fresh install using debian bulls-eye.

git clone https://github.com/getsentry/self-hosted.git sentry
cd sentry
./install.sh

go to webpage at port 9000

### Expected Result

No issues reported after fresh install

### Actual Result

Installed 3 times, same result. After a few seconds an issue is reported: 

![Screen Shot 2022-10-14 at 00 06 00](https://user-images.githubusercontent.com/5460671/195753122-e2a6756c-d444-44b9-8f64-d0d4bdb1ec42.jpg)

The issues continue to be reported growing the number of incidents.

**Comment by lynnagara** [comment]
Errors and transactions pipelines are fully separate now, previously they shared infra. We would need to have two separate post process forwarders, as running both in a single container is no longer supported.

Errors one would need to be like:
`run post-process-forwarder --commit-batch-size 1 --entity errors`

Transactions one would be like:
`run post-process-forwarder --commit-batch-size 1 --entity transactions --commit-log-topic=snuba-transactions-commit-log --synchronize-commit-group transactions_group`

**Comment by hubertdeng123** [comment]
So I'm guessing this is how the docker-compose.yml file would look like 
```
post-process-forwarder-errors:
    <<: *sentry_defaults
    # Increase `--commit-batch-size 1` below to deal with high-load environments.
    command: run post-process-forwarder --commit-batch-size 1 --entity errors

  post-process-forwarder-transactions:
    <<: *sentry_defaults
    command: run post-process-forwarder --commit-batch-size 1 --entity transactions --commit-log-topic=snuba- transactions-commit-log --synchronize-commit-group transactions_group
  ```
