### ISSUE TITLE
Many postgres duplicates keys error in logs

### ISSUE THREAD

**Issue by boskiv** [getsentry/sentry#4517]
Fresh clean install from docker.
```
version: '2'
services:
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=sentry
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  sentry:
    image: sentry
    restart: always
    environment:
      - SENTRY_SECRET_KEY='fwn&3w*9l6rmlkm1h3^hvsh184kv!+8n)9j_)_8y_bn0^d@96v'
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=secret
      - SENTRY_REDIS_HOST=redis
    links:
      - redis:redis
      - postgres:postgres
    ports:
      - "9999:9000"

  cron:
    image: sentry
    restart: always
    environment:
      - SENTRY_SECRET_KEY='fwn&3w*9l6rmlkm1h3^hvsh184kv!+8n)9j_)_8y_bn0^d@96v'
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=secret
      - SENTRY_REDIS_HOST=redis
    command: sentry run cron

  worker:
    image: sentry
    restart: always
    environment:
      - SENTRY_SECRET_KEY='fwn&3w*9l6rmlkm1h3^hvsh184kv!+8n)9j_)_8y_bn0^d@96v'
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=secret
      - SENTRY_REDIS_HOST=redis
    command: sentry run worker
```
```
postgres_1  | ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
postgres_1  | DETAIL:  Key (organization_id, task)=(1, 2) already exists.
postgres_1  | STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "task", "status", "date_completed", "project_id", "data") VALUES (1, NULL, 2, 1, '2016-11-14 11:55:26+00:00', 3, '{"platform": "python"}') RETURNING "sentry_organizationonboardingtask"."id"
worker_1    | 11:57:08 [INFO] sentry.plugins.mail: notification.dispatched (project_id=3L plugin='mail' event_id=15L group_id=15L rule_id=3L digest_key='mail:p:3')
postgres_1  | ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
postgres_1  | DETAIL:  Key (organization_id, task)=(1, 5) already exists.
postgres_1  | STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "task", "status", "date_completed", "project_id", "data") VALUES (1, NULL, 5, 1, '2016-11-14 11:57:08.725019+00:00', 3, '{}') RETURNING "sentry_organizationonboardingtask"."id"
worker_1    | 11:57:09 [INFO] sentry.mail: mail.queued (message_to=(u'admin@exness.com',) event_id=15L group_id=15L message_type='notify.error' message_id='<20161114115709.23.49158@localhost>')
worker_1    | 11:57:09 [INFO] sentry.mail: mail.sent (size=16982 message_id='<20161114115709.23.49158@localhost>')
sentry_1    | 10.130.4.18 - - [14/Nov/2016:11:57:17 +0000] "POST /api/3/store/ HTTP/1.1" 200 366 "-" "raven-python/5.1.1"
postgres_1  | ERROR:  duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96e3b719e55f9a_uniq"
postgres_1  | DETAIL:  Key (project_id, hash)=(3, 616ec0412d59a08c894f051f41bc948c) already exists.
postgres_1  | STATEMENT:  INSERT INTO "sentry_eventuser" ("project_id", "hash", "ident", "email", "username", "ip_address", "date_added") VALUES (3, '616ec0412d59a08c894f051f41bc948c', NULL, NULL, NULL, '10.130.6.151', '2016-11-14 11:57:17.357892+00:00') RETURNING "sentry_eventuser"."id"
worker_1    | 11:57:17 [INFO] sentry.plugins.mail: notification.digested (project_id=3L plugin='mail' event_id=16L group_id=16L rule_id=3L digest_key='mail:p:3')
postgres_1  | ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
postgres_1  | DETAIL:  Key (organization_id, task)=(1, 5) already exists.
postgres_1  | STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "task", "status", "date_completed", "project_id", "data") VALUES (1, NULL, 5, 1, '2016-11-14 11:57:17.466892+00:00', 3, '{}') RETURNING "sentry_organizationonboardingtask"."id"
sentry_1    | 10.129.243.20 - - [14/Nov/2016:11:57:22 +0000] "GET /api/0/broadcasts/ HTTP/1.1" 200 261 "http://sentry.test.env:9999/sentry/dev-12/issues/13/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
sentry_1    | 10.129.243.17 - - [14/Nov/2016:11:57:42 +0000] "GET /api/0/broadcasts/ HTTP/1.1" 200 261 "http://sentry.test.env:9999/sentry/dev-12/issues/13/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
sentry_1    | 10.129.243.20 - - [14/Nov/2016:11:58:23 +0000] "GET /api/0/broadcasts/ HTTP/1.1" 200 261 "http://sentry.test.env:9999/sentry/dev-12/issues/13/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
sentry_1    | 172.27.0.1 - - [14/Nov/2016:11:58:24 +0000] "POST /api/11/store/ HTTP/1.1" 200 366 "-" "raven-python/5.31.0"
worker_1    | 11:58:24 [INFO] sentry.plugins.mail: notification.digested (project_id=11L plugin='mail' event_id=17L group_id=17L rule_id=11L digest_key='mail:p:11')
sentry_1    | 10.130.4.18 - - [14/Nov/2016:11:58:25 +0000] "POST /api/3/store/ HTTP/1.1" 200 366 "-" "raven-python/5.1.1"
postgres_1  | ERROR:  duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96e3b719e55f9a_uniq"
postgres_1  | DETAIL:  Key (project_id, hash)=(3, 616ec0412d59a08c894f051f41bc948c) already exists.
postgres_1  | STATEMENT:  INSERT INTO "sentry_eventuser" ("project_id", "hash", "ident", "email", "username", "ip_address", "date_added") VALUES (3, '616ec0412d59a08c894f051f41bc948c', NULL, NULL, NULL, '10.130.6.151', '2016-11-14 11:58:25.758667+00:00') RETURNING "sentry_eventuser"."id"
worker_1    | 11:58:25 [INFO] sentry.plugins.mail: notification.digested (project_id=3L plugin='mail' event_id=18L group_id=18L rule_id=3L digest_key='mail:p:3')
postgres_1  | ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
postgres_1  | DETAIL:  Key (organization_id, task)=(1, 5) already exists.
postgres_1  | STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "task", "status", "date_completed", "project_id", "data") VALUES (1, NULL, 5, 1, '2016-11-14 11:58:25.907876+00:00', 3, '{}') RETURNING "sentry_organizationonboardingtask"."id"
sentry_1    | 10.129.243.14 - - [14/Nov/2016:11:58:37 +0000] "GET / HTTP/1.1" 302 440 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
sentry_1    | 10.129.243.14 - - [14/Nov/2016:11:58:37 +0000] "GET /auth/login/ HTTP/1.1" 302 597 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
sentry_1    | 10.129.243.14 - - [14/Nov/2016:11:58:37 +0000] "GET /auth/login/sentry/ HTTP/1.1" 200 11056 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
sentry_1    | 10.129.243.14 - - [14/Nov/2016:11:58:37 +0000] "GET /_static/1479122528/sentry/dist/sentry.css HTTP/1.1" 200 52259 "http://sentry.test.env:9999/auth/login/sentry/" "Moz
```
