### ISSUE TITLE
Sentry 21.6.3 - Unable to process events

### ISSUE THREAD

**Issue by amitseth7** [getsentry/sentry#49908]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Sentry 21.6.3 - [relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut

After upgrade using hardstops. 

### Expected Result

Events should be processed. 

### Actual Result

```
nginx_1                                     | 17.93.111.70 - - [29/May/2023:16:18:12 +0000] "POST /api/19/envelope/ HTTP/1.1" 200 41 "-" "sentry.python/0.19.5" "-"
relay_1                                     | 2023-05-29T16:18:12Z [relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut (Local: Message timed out)
relay_1                                     | 2023-05-29T16:18:12Z [relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut (Local: Message timed out)
nginx_1                                     | 17.91.247.70 - - [29/May/2023:16:18:12 +0000] "POST /api/19/envelope/ HTTP/1.1" 200 41 "-" "sentry.python/0.19.5" "-"
```

### Product Area

Issues

### Version

21.6.3

**Comment by amitseth7** [comment]
here is my relay configs 

```
relay:
  #upstream: "http://nginx:80/
  upstream: "http://web:9000/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000} #50MB or bust
  redis: redis://redis:6379
#  geoip_path: "/geoip/GeoLite2-City.mmdb"
http:
  _client: "reqwest"
```
