### ISSUE TITLE
SENTRY_ALLOW_REGISTRATION not working

### ISSUE THREAD

**Issue by drogjh** [getsentry/sentry#5443]
> docker-compose.yml 

```
 version: '2'
  services:
    base:
      build: .
      environment:
        SENTRY_ALLOW_REGISTRATION: 'False'
        SENTRY_SECRET_KEY: 'bnabwe_0t1w=6gr923158ugf)1gc7clx=01zr)ys6zy_f&op*p'
        SENTRY_MEMCACHED_HOST: memcached
        SENTRY_REDIS_HOST: redis
        SENTRY_POSTGRES_HOST: postgres
        SENTRY_EMAIL_HOST: smtp
      volumes:
        - ./data/sentry:/var/lib/sentry/files

    smtp:
      image: tianon/exim4

    memcached:
      image: memcached:1.4

    redis:
      image: redis:3.2-alpine

    postgres:
      image: postgres:9.5
      volumes:
        - ./data/postgres:/var/lib/postgresql/data

    web:
      extends: base
      links:
        - redis
        - postgres
        - memcached
        - smtp
      ports:
        - '9007:9000'

    cron:
      extends: base
      command: run cron
      links:
        - redis
        - postgres
        - memcached
        - smtp

    worker:
      extends: base
      command: run worker
      links:
        - redis
        - postgres
        - memcached
        - smtp
```

> Dockerfile
```FROM sentry:8.16-onbuild```

`SENTRY_ALLOW_REGISTRATION = False`  is not working
