### ISSUE TITLE
Relay Settings Not Shown In UI

### ISSUE THREAD

**Issue by rojinebrahimi** [getsentry/sentry#58989]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.23.0

### Steps to Reproduce

Hi! I am running Sentry v23.10.1 and I have encountered the issue in which I am not able to see Relay settings in UI. Seems Sentry does not load the settings at all!
How can I find any clues related to the issue?

### Expected Result

Show Relay settings page.

### Actual Result

![Screenshot 2023-10-25 at 20 21 58](https://github.com/getsentry/self-hosted/assets/44529498/7d265acb-baea-46ff-a24c-42a191082b5f)

Here is my Relay configuration:
```
 relay:
      mode: proxy
      upstream: "http://web:9000/"
      host: 0.0.0.0
      port: 3000
    logging:
      level: DEBUG
      format: pretty
      enable_backtraces: true
    cache:
      envelope_buffer_size: 8000
      envelope_expiry: 600
    # spool:
    #   envelopes:
    #     path: /tmp
    #     max_memory_size: 100MB
    #     max_disk_size: 500MB
    processing:
      enabled: true
      kafka_config:
        - {name: "bootstrap.servers", value: "kafka:9092"}
        - {name: "message.max.bytes", value: 50000000} # 50MB
      redis: "redis://redis:6379"
      topics:
        events: ingest-events
        attachments: ingest-attachments
        transactions: ingest-transactions
        outcomes: outcomes
        outcomes_billing: null
        sessions: ingest-sessions
        metrics: ingest-metrics
        metrics_sessions: null
        metrics_generic: ingest-performance-metrics
        profiles: profiles
        replay_events: ingest-replay-events
        replay_recordings: ingest-replay-recordings
        monitors: ingest-monitors
        spans: ingest-spans
    http:
      _client: "reqwest"
    geoip_path: "/geoip/GeoLite2-City.mmdb"
```
