### ISSUE TITLE
!! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis'  has no attribute 'RedisSnubaTSDB'")

### ISSUE THREAD

**Issue by OlegYurchik** [getsentry/sentry#60081]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Create docker-compose.yml
```
version: "3"
services:
  postgres:
    ...
  redis:
    ...
  sentry:
    image: getsentry/sentry:dfdf4fb
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY:-passwordpasswordpasswordpassword}
      SENTRY_POSTGRES_HOST: database
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_NAME: ${SENTRY_DB_NAME:-sentry}
      SENTRY_DB_USER: ${SENTRY_DB_USER:-sentry}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD:-P@ssw0rd}
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379
```
2. Run docker compose
`docker compose up -d`

### Expected Result

Running sentry

### Actual Result

Always restarting container with logs:
`!! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis'
 has no attribute 'RedisSnubaTSDB'")`

### Product Area

Other
