### ISSUE TITLE
Missing badge style for debug level logs

### ISSUE THREAD

**Issue by shijistar** [getsentry/sentry#6473]
Version: 8.20
Missing an css rule for `.level-debug` at `shared-components.less`.

```css
&.level-info .error-level {
  background: @blue;
}
&.level-warning .error-level {
  background: @yellow-orange;
}
&.level-error .error-level {
  background: @orange;
}
&.level-fatal .error-level {
  background: @red;
}
&.level-sample .error-level {
  background: @purple;
}
```
