### ISSUE TITLE
Slack Integration Problem

### ISSUE THREAD

**Issue by pavelsshtanko** [getsentry/sentry#66308]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Good afternoon.
I've installed sentry (Sentry 23.5.2 ad182e5)  in my infrastructure, but I'm having trouble setting up notifications in slack.
I created an application for slack according to the instructions
https://develop.sentry.dev/integrations/slack/?referrer=issue-alert-builder and https://docs.sentry.io/product/integrations/notification-incidents/slack/
my app sentry in slack manifest
```
display_information:
  name: sentry.ips.lv
features:
  bot_user:
    display_name: sentry.ips.lv
    always_online: true
  slash_commands:
    - command: /sentry
      url: https://sentry.ips.lv/extensions/slack/commands/
      description: sentry.ips.lv
      should_escape: false
oauth_config:
  redirect_urls:
    - https://sentry.ips.lv/extensions/slack/setup/
  scopes:
    user:
      - links:read
      - users:read
      - users:read.email
    bot:
      - channels:read
      - chat:write
      - chat:write.customize
      - chat:write.public
      - commands
      - groups:read
      - im:history
      - im:read
      - links:write
      - links:read
      - team:read
      - users:read
      - incoming-webhook
settings:
  event_subscriptions:
    request_url: https://sentry.ips.lv/extensions/slack/event/
    user_events:
      - link_shared
    bot_events:
      - link_shared
      - message.im
  interactivity:
    is_enabled: true
    request_url: https://sentry.ips.lv/extensions/slack/action/
    message_menu_options_url: https://sentry.ips.lv/extensions/slack/options-load/
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
```
Next I added to sentry config.yml
```
slack.client-id: '490..............702'
slack.client-secret: '4e8e.........................02f85'
slack.signing-secret: '83c......................................8e7'
slack.verification-token: 'mK...................................X8'
```
settings of my slack application and redeployed sentry.
After that I created alert configurations for slack channels
![image](https://github.com/getsentry/sentry/assets/112397264/d2883177-1302-4e51-ace9-9165a1b47205)
But none of the alerts from different projects made it into the slack channel.
What did I do wrong that needs to be corrected (maybe in the PG database) so that alerts can finally start coming to slack channels.

### Expected Result

showing alerts in a Slack channel

### Actual Result

--

### Product Area

Unknown
