### ISSUE TITLE
Send emails via AWS SES using IRSA to authenticate

### ISSUE THREAD

**Issue by felipeng** [getsentry/sentry#66834]
### Problem Statement

It is possible to send email via AWS SES using SMTP credentials however is not possible via IRSA

### Solution Brainstorm

I developed a workaround which is not ideal but works for now, it would be better if the Sentry provide a way

1. AWS IRSA (`sentry-irsa`) policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "SentrySendEmails",
            "Effect": "Allow",
            "Action": [
                "ses:SendRawEmail",
                "ses:GetSendQuota"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
2. Trust relationship:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123123:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/XYZ"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/XYZ:sub": "system:serviceaccount:monitoring:sentry-worker",
                    "oidc.eks.us-west-2.amazonaws.com/id/XYZ:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```
3. Custom docker-image of sentry with [django-ses](https://github.com/django-ses/django-ses) module:
```
FROM getsentry/sentry:23.6.1
RUN pip --no-cache-dir install django-ses==3.5.2
```
4. Host the custom-sentry-docker-image on ECR
5. Set custom values on Sentry helm-values:
```
images:
  sentry:
    repository: my-docker-repository/sentry
    tag: v23.6.1
config:
  sentryConfPy: |
    AWS_SES_REGION_NAME = os.environ.get("AWS_REGION") # important configuration, otherwise Sentry set the region to us-east-1
mail:
  backend: django_ses.SESBackend
  from: sentry@domain.com
serviceAccount:
  enabled: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123123:role/sentry-irsa
```

I can think of some possible solutions:
* sentry add support to AWS SES mail backend via AWS API not via SMTP
* or the sentry docker image includes the `django-ses` python module
* or easy way to install additional python modules on the helm-values

Another issue that I found creating this workaround is the `ServiceAccount` is shared between all sentry microservices, which is not ideal, for example. The `ServiceAccount` has the annotation to IRSA, which has the AWS policy to access SES. From my understanding only `sentry-worker` needs access to AWS SES to send email, however, since the `ServiceAccount` is share to all others microservices then can access SES. Same applies when using IRSA to access S3, we add the policy to IRSA to access S3, but the ServiceAccount is used for all others microservices as well

### Product Area

Settings - General
