### ISSUE TITLE
Add possibility to setup mentioned user/team in MonitorConfig using Sentry SDK to use it in Alert configuration in Sentry UI

### ISSUE THREAD

**Issue by romanefimchik** [getsentry/sentry#72211]
### Problem Statement

I would like to address every Alert on issue related to Cron Monitor(on schwduled Job) to team-owner of this Job.

Please take a look on image:
![sentry_owner_team](https://github.com/getsentry/sentry/assets/60354106/79d0fc95-7cf1-4c0c-96e6-bc964b764b38)

For example I whould like to set team `@intergations-team` in Alert message in Slack as responsible.

[Java]

When I setup MonitorConfig for partucular Job (I map every Job with owner team in my project config) I use parameter 
```
Map<String, Object> unknown;
```
Bellow you can see my peace of source code:

```
MonitorSchedule schedule = MonitorSchedule.crontab(crontab);
MonitorConfig monitorConfig = new MonitorConfig(schedule);
...
monitorConfig.setUnknown(ImmutableMap.of("owner-team", "@intergations-team"));
```
And then I use this TAG ("owner-team") in Alert is section "THEN perform these actions" (on image)

But currently only `environment` value is used in Alert message in Slack.

There is no any possibility to setup owner team using Sentry SDK and use it in Alert configuration in Sentry UI

### Product Area

Issues

**Comment by gaprl** [comment]
Hey @romanefimchik, Crons does not currently support custom "context" for monitors like the code you mentioned:

```java
// this is currently not supported
monitorConfig.setUnknown(ImmutableMap.of("owner-team", "@intergations-team"));
```

However, there is another way you can accomplish the same.

![CleanShot 2024-06-10 at 15 19 52@2x](https://github.com/getsentry/sentry/assets/1308394/9bec8d90-2da0-42a7-be0a-c09801797fa8)

When creating a new alert rule for your issues, you can:

1. Set the filter for any Cron issues
2. Have it match the `monitor.slug` tag to your monitor
3. Include the `@integrations-team` in the notes field

This way, your team will be mentioned in Slack when when a new issue is created for your monitor. I'll close this issue, but please let me know if you have any other questions.

**Comment by romanefimchik** [comment]
> However, there is another way you can accomplish the same.

@gaprl 
Not the same.
I have 50 scheduled tasks in my project and would like to create Alert rules for them.
With your suggestion I have to create 50 Alert rules, where I can address every Alert (I know owner of each of my 50 tasks).
I have 4 teams in my project.
So, 50 scheduled tasks addressed to 4 teams.

Whith my feature request I only have to create several Alert rules and get addressed team from SDK.
I suggest to confugure in next way team owner and them dynamically in Java configure them to every Monitor -> and Alert.
Please take a look on my configuration (application.yml):
```
...
application:
  tasks:
    scheduled:
      complianceRefresh:
        cron: 0 0 7 * * * # once a day
        maxRuntimeInMins: 180
        max-locked-time-in-millis: 28800000 # 8 hours
        min-locked-time-in-millis: 28740000 # 7 hours 59 minutes
        owner-team: @integration-team

      nonCompliantEmployeesReminder:
        cron: 0 0 9 */14 * WED # once a week
        maxRuntimeInMins: 15
        max-locked-time-in-millis: 28800000 # 8 hours
        min-locked-time-in-millis: 28740000 # 7 hours 59 minutes
        owner-team: @platform-team
       ....
```

And now once again on my code in root post.
On every scheduled task ran - I create/update Monitor.
```
    @Around("executeMethod()")
    public Object checkInSentryCronMonitor(ProceedingJoinPoint joinPoint) throws Throwable {
        ScheduledJob scheduledJob = (ScheduledJob) joinPoint.getTarget();
        String jobName = scheduledJob.getName();
        ...
        MonitorSchedule schedule = MonitorSchedule.crontab(crontab);
        MonitorConfig monitorConfig = new MonitorConfig(schedule);
        ...
        String ownerTeam = taskProperties.getOwnerTeam(jobName);
        monitorConfig.setUnknown(ImmutableMap.of("owner-team", ownerTeam));
```

Where in code
```
taskProperties.getOwnerTeam(jobName)
```
I dynamically get properties for every of 50 tasks.
