### ISSUE TITLE
"Sign in to continue" - but I can't

### ISSUE THREAD

**Issue by Clashsoft** [getsentry/sentry#76384]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Signing in.
Clicking Continue sends me to Register, which is not what I want.

![Image](https://github.com/user-attachments/assets/c92ec78c-b1cc-4954-ac50-45d1ea266b80)

This is a completely new and default installation using https://github.com/sentry-kubernetes/charts.
The only changed values are
```yaml
sentry:
  singleOrganization: false
nginx:
  enabled: false
ingress:
  enabled: true
  # ...
```

### How are you getting stuck?

I cannot sign in with an existing account. I can only create more accounts via Register.

### Where in the product are you?

Sign In

### Link

https://sentry.uni-kassel.dev/auth/login/

### Version

24.5.1
