### ISSUE TITLE
[AoB] Harden sandbox service

### ISSUE THREAD

**Issue by vgrozdanic** [getsentry/sentry#78672]
Service accepts only inbound traffic, all outbound traffic is blocked.

- [x] Test out network policy on kubernetes for disallowing egress traffc
- [ ] Apply it to our cluster
- [ ] Kill demo project and pods/services

**Comment by vgrozdanic** [comment]
Contacted northflank support for this, since it seems that it is not supported currently

**Comment by vgrozdanic** [comment]
There is a way to do it by applying network policies: https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: sandbox
      nfObjectSlug: sandbox
      nfProjectSlug: advent-of-bugs
  policyTypes:
  - Egress
```
