### ISSUE TITLE
Onboarding documentation incorrect

### ISSUE THREAD

**Issue by TakesTheBiscuit** [getsentry/sentry#79822]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

latest

### Steps to reproduce

Follow steps

- https://xx.sentry.io/onboarding/setup-docs/?product=performance-monitoring&product=profiling

The yaml config shown is wrong, it doesn't use an 'options' child/key:

```
when@prod:
      sentry:
          dsn: '%env(SENTRY_DSN)%'
          # Specify a fixed sample rate
          traces_sample_rate: 1.0
          # Set a sampling rate for profiling - this is relative to traces_sample_rate
          profiles_sample_rate: 1.0
```

error thrown:
>   Unrecognized options "traces_sample_rate, prof  
>   iles_sample_rate" under "sentry". Available op  
>   tions are "dsn", "logger", "messenger", "optio  
>   ns", "register_error_handler", "register_error  
>   _listener", "tracing", "transport_factory". 

Correct config seems to be:

```
when@prod:
    sentry:
        dsn: "%env(SENTRY_DSN)%"
        options:
            # Specify a fixed sample rate
            traces_sample_rate: 1.0
            # Set a sampling rate for profiling - this is relative to traces_sample_rate
            profiles_sample_rate: 1.0

```

### Expected result

Expected onboarding instructions to be accurate, i believe the documentation is out of date with the interface/impl

### Actual result

>   Unrecognized options "traces_sample_rate, prof  
>   iles_sample_rate" under "sentry". Available op  
>   tions are "dsn", "logger", "messenger", "optio  
>   ns", "register_error_handler", "register_error  
>   _listener", "tracing", "transport_factory".
