### ISSUE TITLE
Source context not applied to .dart stack traces

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#84680]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the Flutter SDK in a Flutter app
2. Upload the .dart source code to Sentry
3. Send a test event to Sentry

### Expected Result

The stack trace has source code context added based on the upload files. 

### Actual Result

Source context is not applied to the event. 

The code is not minified and build using ShoreBird. 
The stack trace abs_paths is:  `app:///http/skydart_roster_update.dart:109:7`

The uploaded file to the event's release is: `~/http/skydart_roster_update.dart`

Files are uploaded using sentry dart plugin: 
```
sentry_dart_plugin: ^2.4.0
sentry:
  project: [redacted]
  org: [redacted]
  auth_token: [redacted]
  upload_source_maps: true
  upload_sources: true
```

This issue seems to be limited to .dart stack traces. The same process was done with a .js stack trace as test and the uploaded source context was applied to the event. 

The issue was originally [reported on this internal ticket](https://sentry.zendesk.com/agent/tickets/143995).

### Product Area

Issues - Source Maps
