### ISSUE TITLE
Replay Not Found Error on Sentry 24.12.2

### ISSUE THREAD

**Issue by dmuralibabu** [getsentry/sentry#85460]
Hi Team,

Upgraded sentry to 24.12.2 with helm version sentry-26.12.0.

```
Wed Jan 29 16:33:08 2025	superseded	sentry-26.0.0 	24.9.0     	Upgrade complete
Wed Jan 29 16:39:05 2025	superseded	sentry-26.11.0	24.11.2    	Upgrade complete
Thu Feb  6 08:45:17 2025	deployed  	sentry-26.12.0	24.12.2    	Upgrade complete
```

Getting Error Replay not found.

![Image](https://github.com/user-attachments/assets/6cf24d3c-37d1-40cc-8594-e57d8d27216c)

**Comment by billyvg** [comment]
@dmuralibabu do you have the `organizations:session-replay` feature flag enabled in your config?

**Comment by dmuralibabu** [comment]
> [@dmuralibabu](https://github.com/dmuralibabu) do you have the `organizations:session-replay` feature flag enabled in your config?

Looks like it's not enabled.
But I could see the SDK able to send data to Replay.
And when I click open the Replay, I get the error.

![Image](https://github.com/user-attachments/assets/c80fe9c8-f692-4c2f-94ca-9b71fabb8b40)

Please confirm if the below code work to enable session-replay feature.

```
  features:
    orgSubdomains: false
    vstsLimitedScopes: true
    enableProfiling: false
    enableSessionReplay: true
    enableFeedback: false
    enableSpan: false

  # example customFeature to enable Metrics(beta) https://docs.sentry.io/product/metrics/
    customFeatures:
    - organizations:session-replay
````
