### ISSUE TITLE
Generate data for sentry-docs

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry#9643]
We need to update the api to generate data that will work for the new documentation generator.
From looking at the current docs, here's the schema:

```yaml
title: This is a title
path: /this/is/a/path/
method: GET
description: |
  This is a description
path_parameters:
  - name: thisIsAParam
    type: string
    desc: this is a param
# GET
query_parameters:
  - name: thisIsAParam
    type: string
    desc: this is a param
# POST
parameters:
  - name: thisIsAParam
    type: string
    desc: this is a param
authentication: require
example_request: |
    request sample here
example_response: |
    response sample here
```

Jekyll will eventually need a markdown file, that looks like this:

```
---
title: This is a title
path: /this/is/a/path/
etc: …
---
```

Ideally, they should be output [matching the url structure](https://github.com/getsentry/sentry-docs/tree/master/src/collections/_documentation/api), but if need be I can manipulate things once the files are available.
